---
title: "Hw3"
author: "Kat Leigh, Alex Milward, David Segan and Mauricio Collado"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import libraries
library(tidyverse)
library(here)
library(devtools)
library(purrr)

# call function that calculates the yield anomaly for almonds
source("almond_anomaly.R")
```


```{r}
# Dave version

# Instructions for sensitivity analysis:
# Vary 0.0043P^2 parameter using rnorm() function, where n=500. Mean = parameter, stdv = 0.001
# read in data
climate_df <- read.delim(here('clim.txt'), sep = " ")
# run the model
almond_anomaly(climate_df, coef_t1=-0.015, coef_t2=0.0043, coef_p1=-0.07, coef_p2=0.0043, intercept=0.28)
# results
yield_anomaly = almond_anomaly(climate_df, coef_t1=-0.015, coef_t2=0.0043, coef_p1=-0.07, coef_p2=0.0043, intercept=0.28)
# sensitivity analysis 
# normal distribution of parameter 2
input_coef_t2 = rnorm(mean=0.0043, sd = 0.001, n=500)
# apply 500 different par 2 values to function 
# result is 500 lists. each has two columns (year and yield anomalies) and 22 rows
yield_anomaly_sens = input_coef_t2 %>% map(~almond_anomaly(climate_df, coef_t1=-0.015, coef_t2=.x, coef_p1=-0.07, coef_p2=0.0043, intercept=0.28))

###### coef_p2 is not replaced with .x in the function, instead coef_t2 is replaced

head(yield_anomaly_sens)
#convert yield anomaly sens from a bunch of lists to a data frame
yas_df = map_df(yield_anomaly_sens,`[`, c("year","yield"))
# plot
ggplot(yas_df, aes(year,yield, group=year))+geom_boxplot()

```

# Alex version

```{r}
# Alex version

#  rnorm( ) function, where n=500, the mean is equal to the parameter (0.0043), and the standard deviation is 0.001.
# read in climate data
climate_df <- read.delim(here('clim.txt'), sep = ' ')
# make the random data for the sensitivity analysis
coef_p2 <- 0.0043 # set the mean
# Step 1  create data frame to store results 
# how many simulations
number_runs <-  500
#create a dataframe that has rows for each model run
# columns for value of coef_p2
yield_anomalies_sensitivity_res <-  as.data.frame(matrix(nrow=number_runs, ncol=1))
colnames(yield_anomalies_sensitivity_res) <- 'coef_p2'

# Step 2 - generate the test data
test_coef_p2 <- rnorm(n=number_runs, mean=coef_p2, sd=0.001)
yield_anomalies_sensitivity_res$coef_p2 <-  test_coef_p2

#### the table creates a extra column called V1


# Step 3 - apply model to get anomalies for each coef_p2 value
#yield_anomalies_sensitivity_res_test <-  test_coef_p2 %>%
#  map_dfc(~almond_anomaly(coef_p2=test_coef_p2, climate_df=c(rep(climate_df, 500))))
# Step 3 - apply model to get anomalies for each coef_p2 value ~ Did this with one of the ways Naomi did in class

yield_anomalies_sensitivity_res_test <-  test_coef_p2 %>%
  map_dfc(~almond_anomaly(climate_df, coef_p2 = .x))

head(yield_anomalies_sensitivity_res)

# turn it into a data frame to support adding colums
colnames(yield_anomalies_sensitivity_res) <- test_coef_p2

```


```{r}
# mau version

# read in data
climate_df <- read.delim(here('clim.txt'), sep = " ")

# we create our variables
coef_p2_value <- 0.0043 # set the mean
number_runs <-  500 # set the runs

# we create our variable
coef_p2 <- rnorm(n=number_runs, mean=coef_p2_value, sd=0.001)

# sensitivity analysis 
yield_anomaly_sens = coef_p2 %>% 
  map(~almond_anomaly(climate_df, coef_p2=.x)) # we used our runs for coef_p2

head(yield_anomaly_sens)

# we extract the results and then keep them in a dataframe
result_run = map_df(yield_anomaly_sens,`[`, c("year","yield"))

# plot
ggplot(result_run, aes(year,yield, group=year))+
  geom_boxplot()

```