---
title: "Hw3"
author: "Kat Leigh, Alex Milward, David Segan and Mauricio Collado"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# import libraries
library(tidyverse)
library(here)
library(devtools)
library(purrr)
library(scales)

# call function that calculates the yield anomaly for almonds
source("almond_anomaly.R")
source("almond_profit.R")
source("compute_NPV.R")
```

```{r}
# Sensitivity analysis

# read in data
climate_df <- read.delim(here('clim.txt'), sep = " ")

# we create our variables
coef_p2_value <- 0.0043 # set the mean
number_runs <-  500 # set the runs

# we create our variable
coef_p2 <- rnorm(n=number_runs, mean=coef_p2_value, sd=0.001)

# sensitivity analysis 
yield_anomaly_sens = coef_p2 %>% 
  map(~almond_anomaly(climate_df, coef_p2=.x)) # we used our runs for coef_p2

head(yield_anomaly_sens)

# we extract the results and then keep them in a dataframe
result_run = map_df(yield_anomaly_sens,`[`, c("year","yield"))

# plot
ggplot(result_run, aes(year,yield, group=year))+
  geom_boxplot()

```
```{r}
# Net present value

# We calculate the average production+anomaly (maybe this can be part of the model)
result_run1 <- result_run %>% 
    mutate(true_yield=1+yield)

#we assume 1 acres
npv_almond <- almond_profit(almond=result_run1$true_yield, year=result_run1$year)

ggplot(npv_almond , aes(year, netpre, group=year))+geom_boxplot()+labs(title= "Distribution of estimated annual profits from almond production for\n500 different p^2 coefficient values", caption = "Profits calculated based on the following values: price=$2.5/lb., cost=$3800/acre, acre=1, discount=0.12.", y="Profit in current $", x="year")+
  scale_y_continuous(labels=dollar_format())

```




